telegram:
  api-url: "https://api.telegram.org/"
  webhook-path: "https://c9f3-5-167-161-54.ngrok-free.app"
  bot-name: "input @BotName"
  bot-token: "input botToken"
server:
  port: 80
spring:
  activemq:
    broker-url: "tcp://localhost:61616"
    username: "admin"
    password: "admin"
    packages:
      trust-all: true